services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - $EXPOSE_PORT:$VITE_PORT
    
    env_file:
      - $FRONTEND_ENV_LOCATION

    volumes:
      - "/app/node_modules"
    
    container_name: test_container
   
  