name: CI_TEST
on: [push,workflow_dispatch]
jobs:
  test-run:
    runs-on: [self-hosted]
    steps:
      - name: Pull Code
        uses: actions/checkout@v4

      - name: Run docker container
        run: docker compose -f ./Starting\ Project/docker-compose-test.yml --env-file /env/test/.env up --build -d

      - name: Execute test
        run: docker exec -i test_container bash -c "npm run test"

      - name: Clean Up
        if: always()
        run: docker compose -f ./Starting\ Project/docker-compose-test.yml --env-file /env/test/.env down -v
